{{- if eq .Values.govukEnvironment "production" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "govuk-job-request-operator.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ include "govuk-job-request-operator.resourceName" (dict "suffix" "smoke-job-role-binding" "context" $) }}
  namespace: job-request-operator-smoke-test
subjects:
- kind: User
  name: "arn:aws:sts::123456789012:assumed-role/job.req-developer/e2e"
  namespace: job-request-operator-smoke-test
- kind: User
  name: "arn:aws:sts::123456789012:assumed-role/job.rev-developer/e2e"
  namespace: job-request-operator-smoke-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "govuk-job-request-operator.resourceName" (dict "suffix" "smoke-job-role" "context" $) }}
{{- end }}