version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - errname
    - errorlint
    - ginkgolinter
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - nilerr
    - nilnil
    - noctx
    - nosprintfhostport
    - predeclared
    - promlinter
    - reassign
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - usestdlibvars
    - usetesting
    - wastedassign
    - zerologlint
  settings:
    revive:
      rules:
<<<<<<< HEAD
        - name: comment-spacings
        - name: import-shadowing
    modernize:
      disable:
        - omitzero
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
        path: internal/*
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
=======
        - name: dot-imports
          disabled: true
    staticcheck:
      dot-import-whitelist:
        - github.com/onsi/ginkgo/v2
        - github.com/onsi/gomega
    goconst:
      ignore-tests: true
>>>>>>> tmp-original-11-09-26-07-12
