---
repos:
  - repo: local
    hooks:
      - id: manifests
        name: Generate Manifests
        language: unsupported
        entry: make
        args: [manifests]
        exclude: ".github"
        types_or: [go, yaml]
      - id: generate
        name: Generate Go deep copy
        language: unsupported
        entry: make
        args: [generate]
        types: [go]