# This rule is not used by the project govuk-job-request-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over platform.gov.uk.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: govuk-job-request-operator
    app.kubernetes.io/managed-by: kustomize
  name: jobrequest-admin-role
rules:
- apiGroups:
  - platform.publishing.service.gov.uk
  resources:
  - jobrequests
  verbs:
  - '*'
- apiGroups:
  - platform.publishing.service.gov.uk
  resources:
  - jobrequests/status
  verbs:
  - get
