name: Create Versioned Release
on:
  workflow_dispatch:
    inputs:
      level:
        description: 'The semver level of the release'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: main
          fetch-depth: 0
      - run: |
          NEW_VERSION=$(scripts/calculate-semver.sh "${{ github.event.inputs.level }}")
          echo "Calculated new version: $NEW_VERSION"
          git tag "$NEW_VERSION"
          echo "Pushing new tag: $NEW_VERSION"
          git push --tags
  publish:
    uses: ./.github/workflows/publish.yaml
    needs: release
    permissions:
      contents: write
      packages: write
      id-token: write
